### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bookerthegeek** [SpitefulFox/Avaritia#100]
Hello good mod maker!

When have run into an issue. And that is adding more singularities. Many mods add end game blocks, and as nifty as it would be for you to support all of them, I doubt you want to do that. :)

I am requesting a section in the configuration where we can enable custom singularities. 

It would consist of:
- Name of the item to compress
- Quantity of that item
- Display name of the output singularity 
- HEX or RGB color code of the new singularity 

Would also be nice if this was included in an API or able to be implemented via IMC

This would resolve:
- Modpack authors wanting more for their pack
- Other mods wanting to add their own singularities

**Comment by SpitefulFox** [comment]
I'll consider it, but don't hold your breath.

In the meantime, there is ModTweaker support for the compressor.  You can use a separate mod like Custom Things or Tabula Rasa to add custom items and then modtweak some compressor recipes for them.

**Comment by bookerthegeek** [comment]
Thanks for thinking about it. 

We tried that the mods mentioned to add another singularity, but it did not like the animated texture. I'll go double check to see if I did something incorrect. Most likely an error between the keyboard and the chair.

**Comment by Wealthyturtle** [comment]
If that is Not Possible, Could You Add a Feature (Maybe Even a Separate Program) that Generates the Singularity Textures?
Using Custom Things is Fine, but the Singularity Textures are Kinda Hard to Make Manually.
