### ISSUE TITLE
[Suggestion] Ground grinders

### ISSUE THREAD

**Issue by SAIPeregrinus** [SpitefulFox/Avaritia#101]
Since there's AE2 integration there ought to be way to grind up grinders using grinders/pulverizers/etc, and then use ground grinders in ridiculous quantities. This mod _is_ partly about making fun of the ridiculous grinding some other mods require, so requiring the grinding of ground grinders would fit right in.

**Comment by tatsu011** [comment]
Might I also suggest a Compressed Compressor?

**Comment by SAIPeregrinus** [comment]
Or neutronium compressed neutronium?  And neutronium compressed neutronium compressors?
