### ISSUE TITLE
Question, not problem

### ISSUE THREAD

**Issue by blockbreaker1361** [SpitefulFox/Avaritia#102]
As I have looked in 1000 other places to find a place to ask this, I figured I'd do it here. Are there any plans to update to 1.9.4/1.10.2? I know you guys call this a parody mod, but this has to be one of the most useful mods I've ever used.

**Comment by SpitefulFox** [comment]
There are no plans to update this mod.  It's a parody of the modding environment in 1.7.10, it's an intentionally bad mod, and 1.10 is a pain. >.>
