### ISSUE TITLE
[1.7.10] Problem with Skullfire Sword

### ISSUE THREAD

**Issue by Wealthyturtle** [SpitefulFox/Avaritia#103]
Hey,

I'm currently experiencing a problem with Avarita's Skullfire Sword. 
When I killed Wither Skeletons using the Skullfire Sword, they did not have a 100% Wither Skull Drop (~10% Roughly for me)

My Modpack's Mod List:

Applied Energistics 2 - AlgorithmX2 (Version: RV2-Stable-10)
AE2 Stuff - bdew (Version: 0.5.0.56)
Agricraft - InfinityRaider (Version: 1.5.0)
Aquaculture - Shadowclaimer (Version: 1.2.6.21)
Archimedes's Ships - Balkondeur (Version: 1.7.1)
Aroma1997Core - Aroma1997 (Version: 1.0.2.16)
AromaBackup - Aroma1997 (Version: 0.1.0.0)
Aura Cascade - pixlepix (Version: 557)
Automagy - Tuhljin (Version: 0.28.2)
AutoPackager - smbarbour (Version: 1.5.9A)
Avaritia - Assassinfox (Version: 1.11)
Backpacks - Eydamos (Version: 2.0.1)
Baubles - azanor (Version: 1.0.1.10)
BdLib - bdew (Version: 1.9.4.109)
Better Builder's Wands - Portablejim (Version: 0.6.1, Rev 80)
BiblioCraft - JDSinclair (Version: 1.11.5)
BiblioCraft: BiblioWoods Forestry Edition - JDSinclair (Version: 1.7)
BiblioCraft: BiblioWoods Natura Edition - JDSinclair (Version: 1.5)
Big Reactors - ErogenousBeef (Version: 0.43A)
BinniePatcher - Chocohead (Version: 1.8)
Binnie's Mods - Binnie567 (Version: 2.0, Pre 14)
Blood Arsenal - Arcaratus (Version: 1.2.5)
Blood Magic - WayofTime (Version: 1.3.3.17)
Botania - Vazkii (Version: 1.8.249)
Botania: Garden of Glass - Vazkii (Version: None)
Brandon's Core - brandon3055 (Version: 1.0.0.12)
Buildcraft - CovertJaguar (Version: 7.1.1.17)
Calculator - Ollie_Lansdell (Version: 1.9.11)
Carpenter's Blocks - Syntaxial (Version: 3.3.8)
Chance Cubes - turkey2349 (Version: 2.2.1.121)
ChickenChunks - chicken_bones (Version: 1.3.4.19)
Chisel - tterrag1098 (Version: 2.9.5.11)
CodeChickenCore - chicken_bones (Version: 1.0.7.47)
CoFH Core - TeamCoFH (Version: 3.1.3.327)
CoFHLib - TeamCoFH  (Version: 1.1.2.182)
ComputerCraft - dantwohundred (Version: 1.75)
CookieCore - EphysPotato (Version: 1.4.0.11)
DecoCraft2 - RazzleberryFox (Version: 2.3.3)
DefenceTech - aidancbrady (Non-Curse Mod) (Version: 1.0.1.26)
Dense Ores - RWTema (Version: 1.6.2)
Doomlike Dungeons - Blackjar72 (Version: 1.8.10)
Draconic Evolution - brandon3055 (Version: 1.0.2H)
EnderCore - tterrag1098 (Version: 0.2.0.36)
Ender IO - CrazyPants_MC (Version: 2.3.0.429)
Ender Storage - chicken_bones (Version: 1.4.7.37)
Equivalent Energistics - Mordenkainen3141 (Version: 0.6)
Et Futurum - ganymedes01 (Version: 1.5.5)
Ex Astris - insaneau (Version: 1.16.36)
Ex Compressum - BlayTheNinth (Version: 1.1.143)
Ex Nihilo - Erasmus_Crowley (Version: 1.38.53)
ExtraCells 2 - DrummerMC (Version: 2.3.14)
ExtraTiC - JeanGlassmaker (Version: 1.4.6)
Extra Utilities - RWTema (Version: 1.2.12)
Fastcraft - sfPlayer (Version: 1.23)
FastLeafDecay - Olafskii (Version: 1.4)
Forbidden Magic - Assassinfox (Version: 0.575)
Forestry - SirSengir (Version: 4.2.15.63)
FoxLib - Kihira (Version: 0.7.0)
Fruit Charcoal - MinecraftDevin11 (Version: 1.2)
Galacticraft Core - Micdoodle8 (Non-Curse Mod) (Version: 3.0.12.375)
Galacticraft Planets - Micdoodle8 (Non-Curse Mod) (Version: 3.0.12.375)
Gendustry - bdew (Version: 1.6.3.132)
Guide-API - TehNut (Version: 1.0.1.29)
Hats - iChun (Version: 4.0.1)
Hats Stand - iChun (Version: 4.0.0)
HelpFixer - matthewprenger (Version: 1.0.7)
HoloInventory - dries007 (Version: 1.9.1.124)
Hardcore Questing Mode - lorddusk (Version: 4.4.4)
iChunUtil - iChun (Version: 4.2.2)
Iguanas Tinker Tweaks - bonusboni (Version: 2.1.6)
Inventory Pets - Purplicious_Cow (Version: 1.4.8.1)
Inventory Tweaks - Kobata (Version: 1.59, Dev 152)
Iron Chests - progwml6 (Version: 6.0.60.742)
Jabba - ProfMobius (Version: 1.2.2)
JourneyMap - techbrew (Version: 5.1.4P1)
LootBags - Malorolam (Version: 2.0.13)
Magical Crops - Mark719 (Version: 4.0.0_PUBLIC_BETA_3)
Magic Bees - MysteriousAges (Version: 2.4.3)
MalisisCore - Ordinastie (Version: 0.14.3)
Malisis Doors - Ordinastie (Version: 1.13.2)
Mantle - mDiyo (Version: 0.3.2B)
McJtyLib - McJty (Version: 1.8.1)
Mekanism - aidancbrady (Non-Curse Mod) (Version: 9.1.0.281)
Mekanism Generators - aidancbrady (Non-Curse Mod) (Version: 9.1.0.281)
Mekanism Tools - aidancbrady (Non-Curse Mod) (Version: 9.1.0.281)
Metallurgy 4 - JeanGlassmaker (Version: 4.0.9.148)
Metallurgy Classic Machines - JeanGlassmaker (Version: 1.0.3.75)
Metallurgy Core - JeanGlassmaker (Version: 4.0.5.30)
MineFactory Reloaded - skyboy026 (Version: 2.8.1.174)
MineTweaker 3 - StanH (Version: 3.0.10B)
Modular Powersuits - MachineMuse (Version: 0.11.0.301)
Mouse Tweaks - YaLTeR97 (Version: 2.4.4)
MrCrayfish's Furniture Mod - Mr_Crayfish (Version: 3.4.7)
MrTJPCore - Mr_TJP (Version: 1.1.0.33)
Natura - mDiyo (Version: 2.2.0.1)
NEI Addons - bdew (Version: 1.12.14.40)
NEI Integration - tonius111 (Version: 1.1.2)
NetherOres - skyboy026 (Version: 2.3.1.22)
NotEnoughItems - chicken_bones (Version: 1.0.5.120)
NotEnoughResources - Way2muchnoise (Version: 0.1.0.128)
Numina - MachineMuse (Version: 0.4.0.131)
OpenBlocks - OpenMods (Version: 1.5.1)
OpenComputers - Kethtar (Version: 1.6.0.7-RC1)
OpenModsLib - OpenMods (Version: 0.9.1)
OpenModularTurrets - Poenjabiesous (Version: 2.2.4.225)
Pam's HarvestCraft - MatrexsVigil (Version: LB)
Player API - Divisor82 (Version: 1.4)
Portal Gun - iChun (Version: 4.0.0-Beta-6)
Practicalities - jotato (Version: 2.0.0.B2)
Progressive Automation - VanhalMinecraft (Version: 1.6.35)
ProjectE - sinkillerj (Version: 1.10.0)
Project Red - Base - Mr_TJP (Version 4.7.0-Pre-12.95)
Project Red - Compat - Mr_TJP (Version 4.7.0-Pre-12.95)
Project Red - Fabrication - Mr_TJP (Version 4.7.0-Pre-12.95)
Project Red - Integration - Mr_TJP (Version 4.7.0-Pre-12.95)
Project Red - Lighting - Mr_TJP (Version 4.7.0-Pre-12.95)
Project Red - Mechanical - Mr_TJP (Version 4.7.0-Pre-12.95)
Project Red - World - Mr_TJP (Version 4.7.0-Pre-12.95)
Redstone Arsenal - TeamCoFH (Version: 1.1.2.92)
RFDrills - GoldenAppleMinecraft (Version: 1.7.3)
RFTools - McJty (Version: 4.23)
RF Windmills - Piepenguin (Version: 0.7C)
Roguelike Dungeons - Greymerk (Version: 1.5.0B)
Realistic Terrain Generation - WhichOnesPink (Version: 1.1.1)
Runic Dungeons - MrComputerGhost (Version: 1.1.7B)
Sanguimancy - Tombenpotter (Version: 1.1.9.35)
Simply Jetpacks - tonius111 (Version: 1.5.3)
Solar Flux - Nauktis (Version: 0.8B)
Sonar Core - Ollie_Lansdell (Version: 1.1.3)
Storage Drawers - jaquadro (Version: 1.10.1)
Storage Drawers - Forestry Pack - jaquadro (Version: 1.1.2)
Storage Drawers - Misc Pack - jaquadro (Version: 1.1.2)
Storage Drawers - Natura Pack - jaquadro (Version: 1.1.1)
Tails - KitsuneKihira (Version: 1.4.1A)
Tinkers' Construct - mDiyo (Version: 1.8.8)
Thaumcraft 4 - azanor (Version: 4.2.3.5)
Thaumcraft NEI Plugin - DjGiannuzz (Version: 1.7A)
Thaumic Energistics - Nividica (Version 1.0.0.5-AE2-RV2)
Thermal Dynamics - TeamCoFH (Version: 1.2.0.171)
Thermal Expansion - TeamCoFH (Version: 4.1.4.247)
Thermal Foundation - TeamCoFH (Version: 1.2.5.115)
Thermal Recycling - OreCruncher (Version: 1.1.0.5)
TiC Tooltips - squeek502 (Version: 1.2.5)
Tinkers' Mechworks - mDiyo (Version: 0.2.15.106)
Translocators - chicken_bones (Version: 1.1.2.16)
Tinkers' Steelworks - EphysPotato (Forked Mod) (Version: 0.2.15.106)
The Twilight Forest - Benimatic (Version: 2.3.7)
Veinminer - Portablejim (Version: 0.34.1, Rev 473)
Walia - ProfMobius (Version: 1.5.10)
Walia Harvestability - squeek502 (Version: 1.1.6)
Walia Plugins - tterrag1098 (Version: 0.2.0.23)
Wawla - darkh4x (Version: 1.0.5.120)
Witchery - Emoniph (Version: 0.24.1)
WR-CBE-Universal - chicken_bones (Version: 1.4.1.9)

Could you kindly take a look at the mods and tell me if any of these mods might have caused this issue?

After doing some testing, I have confirmed that this is not an Avarita-Side issue, but rather some other mod is causing this.

Thanks!

- Wealthyturtle

**Comment by SpitefulFox** [comment]
It's definitely some other mod's fault, but I have no idea which one.

**Comment by Wealthyturtle** [comment]
Alright then. Thanks

**Comment by TrypChangeling** [comment]
I have identified the incompatible mod as Iguanas Tinker Tweaks. I do not know what to do with this knowledge but put it here.

**Comment by RCXcrafter** [comment]
I use iguana tinker tweaks & avaritia together in my modpack and haven't had any issues with the skullfire sword, I think you might be using a mod that replaces vanilla skeletons with their own version.

**Comment by TrypChangeling** [comment]
The issue occurs with only Avarita, Mantle, TConstruct, and IguanaTinkerTweaks installed.

However, I've just figured out it's Iguana's MobHeads module, which is overriding all of the mob head drops, and seems to be enabled in both modpacks I've used with both mods.

In Iguana's Modules.cfg, the following clears it up:
B:MobHeads=false

**Comment by RCXcrafter** [comment]
Ah okay, I had that turned off already.

**Comment by SpitefulFox** [comment]
Thanks for catching that, TrypChangeling.
