### ISSUE TITLE
you messed up tonkers knockback

### ISSUE THREAD

**Issue by RCXcrafter** [SpitefulFox/Avaritia#105]
Wat did u done 2 tonkers?
http://pastebin.com/1M3HGE8f

That is the crash I get when I hit a pig with a wooden tinkers sword. It seems that you're modifying something with the tinkers knockback and one of my mods doesn't like that. I'm not even going to bother giving you the list of mods (nevermind, it's in the log) because I doubt you could actually use that info. I will of course do more testing to narrow it down for you.

Edit:
Turns out tinkers itself doesn't like what you did to it as I was able to reproduce the crash with just avaritia and tinkers
http://pastebin.com/HAhY1QCw

forge-10.13.4.1614
Avaritia-1.11
Mantle-1.7.10-0.3.2a
TConstruct-1.7.10-1.8.8.DEV.1486950 (yes, my modpack requires this exact version to function)

**Comment by RCXcrafter** [comment]
If you don't have enough time to fix this, I might be able to fix it myself and then make a pull request. Would you like me to try that?

**Comment by RCXcrafter** [comment]
I would just like to notify you that I got impatient and I'm going to try to fix this myself.

**Comment by RCXcrafter** [comment]
I probably should have mentioned that I was using a fork of tinkers construct called tinkered constructor. This version of the mod has apparently changed one of the methods you were using for some stuff.
I was able to fix the issue by simply removing one argument in the tonkers events class.
Would you like me to make a pull request for this or should I just keep this fork separate since it's for such a specific version of tinkers?

**Comment by SpitefulFox** [comment]
Keep it separate if you're using a nonstandard Tinkers build.

**Comment by RCXcrafter** [comment]
Alright, will do.
