### ISSUE TITLE
Possible to remove/reduce speed boost from Infinity boots?

### ISSUE THREAD

**Issue by Akiiseru** [SpitefulFox/Avaritia#106]
Is it at all possible to remove or even reduce the speed boost given by the Infinity boots? I ask because lately using the mod, whenever I use the boots, the speed boost has been causing an insane amount of tick lag, to the point where, if I move far enough in a direction whilst wearing the boots, new chunks completely stop loading, and I'm basically forced to exit and reload the world I'm playing in to be able to do anything.

**Comment by Morpheus1101** [comment]
I will check this in the 1.1x version and adjust this if needed
