### ISSUE TITLE
Tip for updating 1.8+

### ISSUE THREAD

**Issue by Silly511** [SpitefulFox/Avaritia#109]
With the removal of IItemRenderer it would be impossible to have most of the items you have now, how ever I have a tip that might help. Forge allows you to create and load custom IModels. While a custom IModel and IBakedModel would still not allow you to apply custom GL effects like shaders, there is still a hacky way to do it: Make a custom IModel and IBakedModel and return any quads that don't need custom GL effects in the getQuads method(They will render using the vanilla item renderer) and then custom render quads that need GL effects in the isBuiltInRenderer() method. You can get where the item is rendering(ground, gui, hand, etc.) by extending IPerspectiveAwareModel and saving the TransformType provided by handlePerspective() to a static variable. To get the item stack create a custom ItemOverrideList and save the item stack provided by handleItemState() to a static variable, return the custom ItemOverrideList in getItemOverrides(). Hope this helped in the painful transfer between 1.7 and 1.8+.

**Comment by Morpheus1101** [comment]
Majority of the rendering code has all ready been mostly changed to work in 1.1x
