### ISSUE TITLE
ticking player 

### ISSUE THREAD

**Issue by superon** [SpitefulFox/Avaritia#119]
for whatever reason the mc1.7 version on project ozone seems fine but Avaritia-1.10.2-2.1.2.1 crashes, it seems this is bc it allows the player to take on a debuff effect such as hunger and slowness.  in the example case of (1.10...) drinking an "overload brew" from botania it will crash but next time logging in the effect will have "passed" (relogging nulls the effect?), but in the case of using a chest transporter from the titular mod the effect stays on the player (bc the item is carried) therefore the player will receive endless ticking player requiring nbt editing to removing the armor or chest before reloggin can succeed.

**Comment by SpitefulFox** [comment]
This repository is for the 1.7 version.  I don't work on the 1.10 version.  Try here:

https://github.com/Morpheus1101/Avaritia/issues
