### ISSUE TITLE
Possible conflicting mods that prevent Flying

### ISSUE THREAD

**Issue by Lytearro** [SpitefulFox/Avaritia#121]
I have issue with Avaritia in the pack [JaksPack](https://mods.curse.com/modpacks/minecraft/256346-jakspack-1-10-2). Ended up having to remove it but it was causing an issue where you cannot walk up onto stairs from a dirt path, Angel Rings ceased to work, and spectator flight did not work, all but creative flight would not work. I don't know much about the scripting in mods yet, but I couldn't find anything here about it, but also can't seem to find a "Conflict" issue listed here for which mod breaks it.

I'm led to this conclusion because before we added Avaritia, it worked, we scaled back addons until we found which one it was, removed Avaritia, and the issues were fixed.

EDIT: should've done some more research, there is already a issue listed in Morpheus' fork, not sure why it did not show for me when I searched for the variations in google search, oh well. 
https://github.com/Morpheus1101/Avaritia/issues/35

**Comment by SpitefulFox** [comment]
Morpheus' fork is the one for 1.10.  This issue tracker is for 1.7.
