### ISSUE TITLE
[1.10.2] Project ozone lite | Issue with graves and infinity armour

### ISSUE THREAD

**Issue by tonalom** [SpitefulFox/Avaritia#139]
I ran into the issue where using "/suicide" while wearing the infinity armour resulted in me dying, losing my items, but no grave ended up spawning. I looked in console and tried again, no errors at all. I realise 1.10 is an abandoned version, but felt like I should report it either way in case there is something that can be done.

**Comment by SpitefulFox** [comment]
This repo's for the 1.7.10 version.

Report it to the Avaritia 1.1x maintainers.
https://github.com/Morpheus1101/Avaritia/issues
