### ISSUE TITLE
[FIXED] Matter Cluster render bug

### ISSUE THREAD

**Issue by bloop428** [SpitefulFox/Avaritia#14]
Makes 2 boxes of the cosmic shiny stuff: 
![0snpg0c](https://cloud.githubusercontent.com/assets/6138413/9186906/343a4d58-3f7f-11e5-9d87-dfaed3d2d655.png)
Another thing to note: Its the same for non-full clusters, but it's faded.

**Comment by TTFTCUTS** [comment]
That's the missing texture image being used as the cosmic effect mask. Seems the mask is missing somehow.
