### ISSUE TITLE
Port this mod to other game

### ISSUE THREAD

**Issue by ReltHax** [SpitefulFox/Avaritia#141]
I want to port this mod for [Forager](https://store.steampowered.com/app/751780/Forager/).

I can do it?

**Comment by SpitefulFox** [comment]
Forager has mods? :O

**Comment by ReltHax** [comment]
Soon the update connected with the mods will be released

**Comment by SpitefulFox** [comment]
Sure. You can recreate the mod in Forager. I already recreated it for Dwarf Fortress. xD

Link me if you release the mod so I can check it out. And make sure to credit, etc...

**Comment by tehrelt** [comment]
**Hello!** I released your mod to forager!
[Steam Workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1971543469)
