### ISSUE TITLE
no items except the dire table

### ISSUE THREAD

**Issue by jdizzall889** [SpitefulFox/Avaritia#145]
im playing ftb infinity evolved on a server there are no recipes for avaritia at all but the mod is apart of the mod pack there's no equipment, machines or any way to make anything but the dire crafting table
the mod pack is 1.7,10 mod pack version 3 .0.2  avaritia version 1.11

**Comment by SpitefulFox** [comment]
FTB Infinity Evolved has Avaritia set to "recipe-only" mode for some reason, so all of the mod items are taken out except for the table. You'll have to go into the Avaritia config to re-enable them.
