### ISSUE TITLE
Add options

### ISSUE THREAD

**Issue by Gunni** [SpitefulFox/Avaritia#146]
Hey,

I love the Infinity Armor but despise the auto-step feature.

I'd like to be able to turn it off, while still keeping the armor set on...

Thanks

**Comment by SpitefulFox** [comment]
I too despise auto-step.  Are you sure you're reporting on the right version of the mod?  Because I explicitly never added auto-step to the mod in 1.7.

**Comment by Gunni** [comment]
I have the Dungeons, Dragons and Space Shuttles modpack v7.4a. It contains (amongst other things):
- Avaritia 3.3.0
- Refined Avaritia 1.12.2-2.6

**Comment by Gunni** [comment]
I'm sorry, I just noticed this repo is for an older version of the pack, I'll be on my way then :)

**Comment by SpitefulFox** [comment]
Good luck!  I hate auto-step. x3
