### ISSUE TITLE
All fractured ores are called Unknown Fractured Ore

### ISSUE THREAD

**Issue by bloop428** [SpitefulFox/Avaritia#15]
Title says it all, every ore has the same name: 
![2015-08-10_16 46 58](https://cloud.githubusercontent.com/assets/6138413/9186926/877c7a5e-3f7f-11e5-9820-ca0df8a75839.png)

**Comment by TTFTCUTS** [comment]
Fixed. NBT tag-reading issue after I fixed an ID problem.
