### ISSUE TITLE
Shader texture issue

### ISSUE THREAD

**Issue by Mattyfire29** [SpitefulFox/Avaritia#150]
Hi
I'm developing a series to record
In this series I also want to use the Avaritia mod
But armor and Sword have a cosmos texture bug
it is as if only the cosmic png 0 is worth
it looks like this. look the cosmos in the sword
![2021-03-26_08 49 45](https://user-images.githubusercontent.com/81408620/112599607-79433280-8e10-11eb-8934-c60d1d3c6495.png)
I wish it looked like this, with different stars
https://i.ytimg.com/vi/PZbnFFE3qxE/maxresdefault.jpg
how can i solve?

**Comment by SpitefulFox** [comment]
I don't understand?  It looks like it should in the screenshot?  The one in that youtube thumbnail is the one that's broken.

**Comment by Mattyfire29** [comment]
you are right. however, I find that the miniature one has all the cosmic pngs in the shader.
So I think the variants of the stars are beautiful. is there any way to change it?
I am also attaching a detailed photo
In avaritia jar was all these
![image](https://user-images.githubusercontent.com/81408620/112610020-86661e80-8e1c-11eb-91d0-55225a3428f2.png)
![image](https://user-images.githubusercontent.com/81408620/112610039-8c5bff80-8e1c-11eb-9314-26843f5843b3.png)
![image](https://user-images.githubusercontent.com/81408620/112610541-1b691780-8e1d-11eb-9f5b-5dbadafe93d2.png)
![image](https://user-images.githubusercontent.com/81408620/112610548-1e640800-8e1d-11eb-821b-902dda00091c.png)
![image](https://user-images.githubusercontent.com/81408620/112610558-215ef880-8e1d-11eb-8b80-825f47a08322.png)
![image](https://user-images.githubusercontent.com/81408620/112610569-23c15280-8e1d-11eb-9e6d-b89023f0477a.png)
![image](https://user-images.githubusercontent.com/81408620/112610582-26bc4300-8e1d-11eb-8ef5-ebda971187a5.png)
![image](https://user-images.githubusercontent.com/81408620/112610602-2a4fca00-8e1d-11eb-9ca4-f71a22252dd0.png)
![image](https://user-images.githubusercontent.com/81408620/112610611-2d4aba80-8e1d-11eb-9423-2dc1adef7e93.png)
![image](https://user-images.githubusercontent.com/81408620/112610625-3176d800-8e1d-11eb-8a44-89f76ee4422b.png)
The shader only consider cosmic_0 png
is there a way to get them all considered?

**Comment by SpitefulFox** [comment]
Even if there was a way to change it, the dev environment for 1.7.10 is broken these days and I don't really have the energy to try and get it working just for such a minor cosmetic tweak. Sorry.

**Comment by Mattyfire29** [comment]
don't worry
another thing in this series i want to use a modified version of avaritia, maded by me. Can I use it in video?

**Comment by SpitefulFox** [comment]
Sure!
