### ISSUE TITLE
Please add clear function to dominate the sword of worldwide.

### ISSUE THREAD

**Issue by love-code-yeyixiao** [SpitefulFox/Avaritia#153]
If you can do it, it is recommended that the right dominate the sword of worldwide labels on (NBT) can modify the mode, and add remove function.
The remove function can invoke the Entity object. (this implementation in 1.16.5 version, but I don't know 1.12 x version is there?)

**Comment by SpitefulFox** [comment]
I don't understand what you're asking for. o.O

But it sounds like you want this implemented in one of the newer versions. This branch of the repo is for the 1.7.10 version.  Try submitting your issue here instead:

https://github.com/Morpheus1101/Avaritia/issues
