### ISSUE TITLE
Move items to crafting[quickcraft]

### ISSUE THREAD

**Issue by rafalohaki** [SpitefulFox/Avaritia#156]
![image](https://user-images.githubusercontent.com/20607107/200825061-a0b13983-93bf-483c-94ca-3ddb0d99b0ba.png)
![image](https://user-images.githubusercontent.com/20607107/200825071-503d0122-e7a3-4c21-a1a0-9bc983b7a7d8.png)

when i try quickcraft, i get error.
logs of error.
https://mclo.gs/HhI4b8Z

**Comment by SpitefulFox** [comment]
Wrong repo. Post it here instead:

https://github.com/Morpheus1101/Avaritia/issues
