### ISSUE TITLE
Can I put Avaritia into the modpack I am working on.

### ISSUE THREAD

**Issue by rhghunter** [SpitefulFox/Avaritia#158]
I know this isn't an issue or anything, this was the only that I can find to ask you. I'm working on a lightweight Modpack for people who can't afford a gaming pc. I was also planning to leave all of the mod links for all of the mods I used. It is also my first time making a modpack so your mod wouldn't be in the best modpack. Any answer I'm fine with.

**Comment by SpitefulFox** [comment]
Yes, Avaritia is allowed in any modpacks.  I developed Avaritia on a really crappy computer that couldn't even run the big modpacks, so I always appreciate people making lightweight packs.
