### ISSUE TITLE
Fractured ore of some modded ores have no recipe

### ISSUE THREAD

**Issue by bloop428** [SpitefulFox/Avaritia#18]
Even though tin ore from one mod has a working fractured version with recipes, the tin ore from Mekanism creates a whole different fractured ore instead of the existing one and the new fractured tin has no recipes, so it cant be smelted.

**Comment by demethan** [comment]
Nickel from electricraft, osmium from mekanism don't have recipes. 

Doesn't seem to have a item name to fix with minetweaker.

Thanks.

**Comment by SpitefulFox** [comment]
Everything has an item name.  Hold the item in your hand and use /mt hand
