### ISSUE TITLE
Asgardandelion doesn't have proper name when looking at with Wand of the Forest

### ISSUE THREAD

**Issue by bloop428** [SpitefulFox/Avaritia#19]
tile.botania:flower.asgardandelion.name
![screenshot_6](https://cloud.githubusercontent.com/assets/6138413/9287436/a2fd15a2-42c9-11e5-9c42-6dd0d747bb64.png)

**Comment by SpitefulFox** [comment]
Known glitch with add-on flowers.  Problem is on Botania's end.
