### ISSUE TITLE
Weird stuff happening in my client !

### ISSUE THREAD

**Issue by AngieTheDemoness** [SpitefulFox/Avaritia#27]
![2015-08-30_18 28 15](https://cloud.githubusercontent.com/assets/13290482/9568284/431b7cb8-4f45-11e5-80bb-23e03a6618ff.png)
![2015-08-30_18 28 29](https://cloud.githubusercontent.com/assets/13290482/9568285/431de2aa-4f45-11e5-8fa8-11ccaf5bdc87.png)
Was just messing around and this happened. Just ask me for more informations if you need.

**Comment by SpitefulFox** [comment]
This seems relevant to the problem: http://pastebin.com/66Xbq801

**Comment by SpitefulFox** [comment]
I blame @CandiceJoy

**Comment by CandiceJoy** [comment]
It's not my fault!  You salted your hashes wrong!

**Comment by SpitefulFox** [comment]
* assaults @CandiceJoy 's hashes *

**Comment by SpitefulFox** [comment]
@AngieTheDemoness were you playing on a server when you got these weird glitches?

**Comment by SpitefulFox** [comment]
Candice has been getting the same problems while playing on Tlove's server, but playing in singleplayer displays the items correctly for some reason.

**Comment by SpitefulFox** [comment]
Angie has confirmed that she was getting these glitches in multiplayer but not singleplayer.  The infinitato glitch appears to be connected to how Alfheim is throwing an error on dedicated servers, which causes the try {} catch {} loop to abort early and not add the Infinitato server-side.  No idea why the Morvy box is acting up, though.
