### ISSUE TITLE
Texture Stitching Error

### ISSUE THREAD

**Issue by BluSunrize** [SpitefulFox/Avaritia#32]
https://github.com/SpitefulFox/Avaritia/blob/f87c37a4c7fb5f6bca8bf41d13efa8893e1a2cac/src/main/java/fox/spiteful/avaritia/render/LudicrousRenderEvents.java#L33
https://github.com/SpitefulFox/Avaritia/blob/f87c37a4c7fb5f6bca8bf41d13efa8893e1a2cac/src/main/java/fox/spiteful/avaritia/render/LudicrousRenderEvents.java#L47

This will only work if the existing texturemaps are blocks(0) and items(1). But there are methods to register custom texture maps (IE does this for its revolvers), which leads to this event being fired again, and you trying to stitch your textures into my revolver sheet.

To fix this, just check for the sheet you want, rather than the ones you don't want,
if(event.map.getTextureType()!=1)
   return;

**Comment by SpitefulFox** [comment]
123 not it!

**Comment by TTFTCUTS** [comment]
Yeah, I knew about this back when you animated the revolvers, but I hadn't gotten around to fixing it yet. It's already a todo for me.
