### ISSUE TITLE
Using shovel crashes

### ISSUE THREAD

**Issue by Vanir2314** [SpitefulFox/Avaritia#37]
I crash when mining stuff (grass, dirt gravel were tested) with Avaritias shovel.
Pack: For the Love of Adventure
Version: 0.2c
Forge: 10.13.4.1448

Error:
java.lang.NullPointerException
	at fox.spiteful.avaritia.LudicrousEvents.canHarvest(LudicrousEvents.java:272) ~[LudicrousEvents.class:?]

fml log: http://www.mediafire.com/download/bcrurwe4jqrkq5a/fml-client-latest.log
crash report: http://pastebin.com/n1h2x6VS

**Comment by SpitefulFox** [comment]
Hurray for getTagCompound returning null! \o/

**Comment by SpitefulFox** [comment]
Enchant the shovel or switch it to Destroyer Mode and back to prevent it from causing a crash.  Will be fixed in the next patch.
