### ISSUE TITLE
Compressor only gives one output when output has items

### ISSUE THREAD

**Issue by bloop428** [SpitefulFox/Avaritia#38]
In a mod I am using to learn more about modding I added a new compressor recipe that outputs more than one item. It does as expected and gives 8 bricks the first time, but if I don't remove those bricks from the output, then it will only give me one brick.

Relevant code: CompressorManager.addRecipe(new ItemStack(Blocks.brick_block, 8), 1, new ItemStack(Blocks.diamond_block));

Pictures:
    First Item:
![screenshot_7](https://cloud.githubusercontent.com/assets/6138413/9857511/cfdae270-5acf-11e5-86b5-34f943035e99.png)
    Second Item:
![screenshot_8](https://cloud.githubusercontent.com/assets/6138413/9857514/d403a4c2-5acf-11e5-909e-e561006350dc.png)

**Comment by SpitefulFox** [comment]
Thanks.  I'll get that looked at when I have time.
