### ISSUE TITLE
Error with MineFactoryReloaded Compat

### ISSUE THREAD

**Issue by Xen1290** [SpitefulFox/Avaritia#4]
Hi @SpitefulFox , @TTFTCUTS ,  first, awesome mod! Second, this error appear in console:
https://gist.github.com/Xen1290/6157396329d7892fe3fe
The cause of this I think is here:
https://github.com/SpitefulFox/Avaritia/blob/master/src/main/java/fox/spiteful/avaritia/compat/Compat.java#L254-L256
The name of MFR Pinkslime is:  MineFactoryReloaded:pinkslime , not: MineFactoryReloaded:mfr.pinkslime
Tested with:
MineFactoryReloaded-[1.7.10]2.8.0-104 (Latest stable version)
Avaritia (build in this moment), https://github.com/SpitefulFox/Avaritia/commit/802e18e4893dd579b3dd093a2e76f4cbc33a7163)

**Comment by SpitefulFox** [comment]
Thanks!
