### ISSUE TITLE
Crash when using Planet Eater

### ISSUE THREAD

**Issue by RIMQ** [SpitefulFox/Avaritia#41]
When i tried to break a dirt block my game crashed

Mod Version: 0.21c
Forge: 10.13.4.1448 

Crash File
MultiMC: http://paste.ee/p/wPrsA
Minecraft Crash Log: http://paste.ee/p/iAjjJ

**Comment by SpitefulFox** [comment]
Hurray for more Mojang methods returning null when they shouldn't!

To avoid crashes, enchant the shovel or switch it to destroyer mode (Shift + Right Click) and back.
