### ISSUE TITLE
Infinity Pickaxe & Mob Spawner Quirk

### ISSUE THREAD

**Issue by GeoTerra** [SpitefulFox/Avaritia#49]
Rather interestingly, I found out that the "Infinity Pickaxe" (Can't remember the name right now) can duplicate Mob Spawners the other night, only if you have a mod installed that allows you to break and pick up Mob Spawners (like EnderIO). I was playing the "For The Love of Adventure" modpack from CurseVoice at the time.

I remember Spiteful mentioning to me at one point that the Pickaxe applies a x4 increase to block drops on top of the Fortune X it comes with. I believe that this multiplier is to blame for the four Skellie & 4 Zombie Spawners I got out of a Thaumcraft Hollow Hill.

Considering that Avaritia IS a end-game (parody) mod, I can see why, potentially, this wouldn't matter, but I decided to be responsible and bring this up regardless. I did find this rather humorous when I discovered this "unintended feature".

**Comment by ZiaAvenicia** [comment]
![Bug](http://i.imgur.com/oO1wA8B.jpg)
