### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by Xen1290** [SpitefulFox/Avaritia#5]
Hi, @TTFTCUTS , @SpitefulFox , I get this crash on startup:
https://gist.github.com/Xen1290/4b4b53e4f3ac664ca85e

Tested with:
Avaritia (build in this moment), 802e18e)
Forge #1492

**Comment by SpitefulFox** [comment]
Should be fixed.  Try it now.

**Comment by Xen1290** [comment]
Thanks!
