### ISSUE TITLE
Error in console Forestry 4.x

### ISSUE THREAD

**Issue by Xen1290** [SpitefulFox/Avaritia#50]
https://gist.github.com/Xen1290/892017472820439c57b6
Forestry 4.0.6 on curseforge
Forge #1492

**Comment by SpitefulFox** [comment]
What version of Avaritia and what version of Forestry?  What modpack?

**Comment by Xen1290** [comment]
Oh, sorry:
Avaritia https://github.com/SpitefulFox/Avaritia/commit/63902077407c3eb92575368517fc0fbce532c03c
Forestry 4.0.6 
Custom Modpack.
 If you need the entire mod list let me know.

**Comment by Xen1290** [comment]
Same result with Forestry 4.2.x @SpitefulFox

**Comment by Xen1290** [comment]
?

**Comment by SpitefulFox** [comment]
Update to the latest version and keep bees disabled.

**Comment by Xen1290** [comment]
Oh, ok. Thanks for the answer!
