### ISSUE TITLE
Suggestion: Ultimate Quantum Hyper Compressed Solar Panel 9000+?

### ISSUE THREAD

**Issue by akvgergo** [SpitefulFox/Avaritia#54]
So efficient, it can generate RF even in the middle of the night. Feels like it would fit in the theme of the mod. Thoughts? :P

**Comment by SpitefulFox** [comment]
We already have the Creative Energy Cell for that, though. :o

**Comment by akvgergo** [comment]
Yes, it would be fun to ridicule those couple mods that name their solar panels like this though. Plus, 'Ultra efficient solar panel' sounds a bit more appealing than 'Creative energy cell'.
