### ISSUE TITLE
No Armor or Tools?

### ISSUE THREAD

**Issue by Calenria** [SpitefulFox/Avaritia#59]
Invalid registration attempt for an Ore Dictionary item entrys in [fml-server-latest.log](https://gist.github.com/Calenria/34ba5c4bb5d07db84f24)

[No Armor or Tools in the Creative Tab/NEI](http://i.imgur.com/JU9JFO4.png)

Infinity Ingots and Catalyst do not have a recipe.

[Full Server Log](https://gist.github.com/Calenria/b9bceffe3aca20f9906b)

Versions:
* forge: 1.7.10-10.13.4.1566
* NotEnoughItems-1.7.10-1.0.5.118-universal.jar
* Avaritia-0.22c.jar

**Comment by TTFTCUTS** [comment]
By the looks of the items (no halos, so the fancy renderers weren't initialised), the tools and things wouldn't be available because the SECRET CONFIG(tm) is turned off, and only allows access to the basic parts of the mod.

**Comment by Calenria** [comment]
omg... got it, sry :)

**Comment by Zsashas** [comment]
Out of curiosity, what mod's tab is that to the right of the Thaumcraft one?

**Comment by SpitefulFox** [comment]
Looks like Ancient Trees.
