### ISSUE TITLE
Crash when using the Akashic Records

### ISSUE THREAD

**Issue by bloop428** [SpitefulFox/Avaritia#6]
Simple, the game crashes when using the Akashic Records item. FML Log: http://pastebin.com/EsMwZBR0

**Comment by SpitefulFox** [comment]
I'm unable to reproduce this crash.  Did you try it a second time to see if it still crashes?

**Comment by Nukeer9578** [comment]
I can reproduce this crash using the latest version (commit c61d4abc0bca3e00f4224033d5294ae7c67c638c).
Log: http://pastebin.com/H88VT1wi
Still crashes when only Thaumcraft (4.2.3.5) and Avaritia are present in the instance.
Log:http://pastebin.com/j6GeC6RQ
When it crashes it still gives you 999 of each aspect. Putting it in an Autonomous Activator uses up the item, but does not crash, so I think it is a rendering problem. Is it possible, that Thaumcraft just can't handle displaying all the aspects at once on the screen?
