### ISSUE TITLE
Morv in a Box?

### ISSUE THREAD

**Issue by Zsashas** [SpitefulFox/Avaritia#64]
I'm curious about what it's supposed to do...when I used it, it sent me to the Lava dimension from Deeper Caves. However, it was taking a long time loading so I left the world and re-joined...only to find myself in the Near Nether dimension of Deeper Caves. Neither of these seems like the intended destination or result.

The mod, for reference: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2350259-deeper-caves-go-beyond-the-void-alpha-4000

**Comment by SpitefulFox** [comment]
It's supposed to send you to the Alfheim dimension.  Probably a dimension ID conflict.

**Comment by Zsashas** [comment]
Oh now I remember...I had to disable the Alfheim content because the neither mod had a dimension ID conflict. Derp goldfish memory. Maybe have a backup behaviour in case Alfheim is disabled?

**Comment by SpitefulFox** [comment]
It's a debug item that is ONLY available through cheating.  So no.

**Comment by Zsashas** [comment]
Perhaps have it enabled/disabled along with the Alfheim content, then, as it appears to be part of it.
