### ISSUE TITLE
Soarleander does nothing

### ISSUE THREAD

**Issue by Zsashas** [SpitefulFox/Avaritia#66]
Unless I am seriously misunderstanding how it works. I had it surrounded by several live chickens, and both raw and cooked chicken, plus some eggs for good measure. Nothing happened.

**Comment by SpitefulFox** [comment]
That's the joke.

**Comment by Zsashas** [comment]
[the joke]

[me]


whooosh lol.

**Comment by Merrit** [comment]
I don't get the joke apparently.

**Comment by SpitefulFox** [comment]
The Soarleander is named after Soaryn.  It does nothing, just like Soaryn does nothing.

**Comment by Merrit** [comment]
Never heard of him, had to look up the name just now.
Even after reading the wiki page about him, it still doesn't really mean anything to me.

For those of us out of the loop, probably should've said something in-game to let us know. Chicken-eating flower doesn't really seem more outlandish than a cake-eating flower after all :)

**Comment by SpitefulFox** [comment]
Fair.  Main reason why I try to avoid little in-jokes like this.  The flower wasn't my baby, though. xP
