### ISSUE TITLE
Sword of the Cosmos & Witchery Vamprism

### ISSUE THREAD

**Issue by Mohron** [SpitefulFox/Avaritia#68]
Any chance you could make the Sword of the Cosmos deal fire damage on hit or really anything to make it kill Vampires from witchery?  A sword this powerful seems like it should be able to kill an immortal!

**Comment by Zsashas** [comment]
Does the Skullfire Sword do fire damage? If not, maybe it should. I like having to make a specific weapon to be effective in killing vampires, and not just use the same thing that kills everything else.

**Comment by Alexismachina** [comment]
it still doesn't work with some mods that give fire resistance , i can still take hits from the infinity sword, but it would take you forever if you had to get all the mods to make it work so "shrug"
