### ISSUE TITLE
Skullfire Sword doesn't work

### ISSUE THREAD

**Issue by Zsashas** [SpitefulFox/Avaritia#72]
Not a single skeleton skull, wither or normal, after using it to kill 128 skeletons.

**Comment by SpitefulFox** [comment]
Works just fine for me.

**Comment by Zsashas** [comment]
Are there certain conditions for it to work? I just used a couple of stacks of spawn eggs in the overworld, in my superflat test world, at night.

**Comment by SpitefulFox** [comment]
There's no special conditions for it.  It should just work.  Are you using the latest release?  Any other mods present?  Using regular vanilla skeletons and not SpecialMobs?

**Comment by Zsashas** [comment]
Don't have Special Mobs or anything else that changes vanilla skeletons. Latest release. Clearly, it SHOULD be working...will test more.

**Comment by Sky-Evil** [comment]
it doesn't work for me either

**Comment by SpitefulFox** [comment]
Once again, it works just fine for me.  Give me details like what version you're using, what other mods do you have installed instead of "It dun work", please.
