### ISSUE TITLE
The Challenge; Avaritia style bosses & stuff

### ISSUE THREAD

**Issue by Renegade2** [SpitefulFox/Avaritia#73]
After playing with alot of different mods,things become less challenging.you have 30 heart canisters,full ichor robes,maxed tinkers' tools, full spell book of power spells,and so on.You could nerf everything,but where's the fun in that? My idea was for the most challenging bosses in the game; Bosses with 3000+ hp,powerful magic,and enough weapon damage to kill you in 3 hits! Right now I dont have any ideas for any bosses,but im sure someone can come up with something.

The next idea is for thaumcraft.After using many different addons,i noticed there aren't alot of high power wand focuses.After you get a powerful wand,there's nothing to really use if for,but for a fire focus/etc.with some avaritia bosses,they could drop infusion components to make high power wand focuses.

**Comment by DaMachinator** [comment]
I like Witchery's puzzle-type bosses, where you have to discover (or read on the internet :sigh:) how to kill the boss, and if you don't use (one of) the correct solutions, it is invulnerable, and you will die, rather than gearing up, finding the weapon with the highest DPS, and turning on an autoclicker.

**Comment by Zsashas** [comment]
I will always support additional wand foci, although I don't know what else there could be that other addons haven't already made...

Just slapping more HP or defense or whatever on a boss simply makes it take longer, doesn't necessarily make it more interesting. Like DaMachinator said, bosses with gimmicks are usually much more fun. Witchery's bosses are a good example, as well as the Gaia Guardian from Botania, and the Darknuts from Zelda Sword Skills.

**Comment by DaMachinator** [comment]
Wand foci have been done to death, but more powerful versions of the existing foci could be cool - a shock focus that calls lightning down from above (and can charge creepers and do other lightning things again), or a fire focus that ignites everything in a massive AoE.

**Comment by Zsashas** [comment]
I have used the Focal Manipulator, but I still think there are more things that could be done, particularly with summons and AoE foci.

I do like the Tainted Magic ones...now if only Thaumic Tinkerer would bother to add upgrades for theirs.

**Comment by DaMachinator** [comment]
All the Thaumic Tinkerer ones have upgrades, mostly the bog-standard potency, frugal, and fortune

**Comment by Zsashas** [comment]
Actually no. None of them have anything.

**Comment by DaMachinator** [comment]
I could have sworn I was able to enchant some of them....

Whatever, its a wonder that mod still works. It's been around forever.

**Comment by Zsashas** [comment]
Is TT still being updated? Maybe they'll add upgrades soon then...

**Comment by DaMachinator** [comment]
It's changed hands several times...I don't know who owns it now.

**Comment by DaMachinator** [comment]
Last commit was by nekosune 10 days ago

**Comment by DaMachinator** [comment]
So yes, active development

**Comment by resinate** [comment]
use Apocalypse-1.7.10-0.0.6 this will make mobs harder over time. 8000 hp chaos dragons FTW lol

**Comment by DaMachinator** [comment]
>8000 hp chaos dragons

Signalum crossbow OP.
