### ISSUE TITLE
[Request] Config Options

### ISSUE THREAD

**Issue by Zsashas** [SpitefulFox/Avaritia#77]
An option to disable fractured ores (to fix the crash with RotaryCraft and NEI) and an option to change the dimension ID (to fix a conflict with Deeper Caves, which also has no ID config).

**Comment by SpitefulFox** [comment]
No dimension = No dimension ID

**Comment by Zsashas** [comment]
What about the Fractured Ores one?

**Comment by SpitefulFox** [comment]
It shouldn't be.  The dimension was fucking removed.  Are you using some old version of the mod?

**Comment by Zsashas** [comment]
Apparently so, although the dimension's removal isn't in the changelog...

The fractured ores are still an issue.

**Comment by SpitefulFox** [comment]
So, you've been pestering me about the dimension ID all this time even though I removed the entire dimension back in January?
