### ISSUE TITLE
Not an issue, but a licence question

### ISSUE THREAD

**Issue by parzivail** [SpitefulFox/Avaritia#8]
Is it alright if I implement your IHaloRenderItem and FancyHaloRender in my own mod, with credit in the code? It's a great idea and I had no idea how to go about implementing it myself.

Thanks!
Parzi

**Comment by SpitefulFox** [comment]
Just make sure to give credit and it's fine. ^_^

**Comment by TTFTCUTS** [comment]
(But please at least wait until the mod's been out a bit...)

**Comment by parzivail** [comment]
(Alright, this mod won't be out until late august :P)
