### ISSUE TITLE
Neutronium Rods not powerful enough

### ISSUE THREAD

**Issue by SpitefulFox** [SpitefulFox/Avaritia#80]
Yeah.

**Comment by Morpheus1101** [comment]
Could you elaborate more on this?

**Comment by SpitefulFox** [comment]
If I remember right, I think this is about the neutronium TiCon material still being a weaker handle material than ExtraTiC's enderium before enderium got nerfed.

**Comment by TTFTCUTS** [comment]
Yeah, I initially pitched the balance of neutronium as a tool sidegrade and weapon upgrade from manyullyn, but then ExtraTiC was like "lol, all your materials suck" and went overboard.

**Comment by SpitefulFox** [comment]
Silly CUTS!  Balance is for banks!
