### ISSUE TITLE
Non creative flight

### ISSUE THREAD

**Issue by Polypo** [SpitefulFox/Avaritia#84]
This issue might be adressed allready however, 

for those of us with less powerfull computers creative flight is a pain because we literally can't fly whenever there's a bit of client lag going on, adding an option to add non-creative flight (as in draconic evolution chestplate, or jetpacks) would be awesome. 
thank you for your time

**Comment by Vazkii** [comment]
wat

**Comment by SpitefulFox** [comment]
Ummm, I can only assume you're talking about how the double jump to initiate flight doesn't work when your FPS is too low?  I have a really bad PC myself, so I run into that a lot.

Anyways, I'm not implementing an entirely new flight system just to cater to low-end computers.  Sorry.
