### ISSUE TITLE
disable certain recipes?

### ISSUE THREAD

**Issue by resinate** [SpitefulFox/Avaritia#86]
is there a way to disable certain recipes in the 9x9 crafting grid with your mod or minetweaker?

**Comment by SpitefulFox** [comment]
Yes.  It explains how to remove recipes with Minetweaker on the mod's page.

http://minecraft.curseforge.com/projects/avaritia

**Comment by resinate** [comment]
yea it works with 3x3 standard recipes but it doesnt work for the custom 9x9o ones
