### ISSUE TITLE
Not Op enough, and needs more stuff.

### ISSUE THREAD

**Issue by nitro0226** [SpitefulFox/Avaritia#91]
Sure everything is op but not op enough. You can still die with the armor on even and I think some mods actually have a way to block, *cough* Mine and Blade Battlegear Shields *cough*. Also, tiering the armor with several different things and adding more buffs to the armor would also be nice. Suffocation immunity, water breathing, night vision, step assist, magic damage protection, Ars Magica effect negation, and maybe some others such as increased mana and health regen. Also, two tiers of armor and or tools: Tier 1 is Temporal and Spacial, Tier 2 is infinity. Also, add in a sort of powerstaff combining the infinity tools similar to draconic evolution and others. Otherwise, one of the best and most op mods I have ever seen. 

P.S. Maybe add a way to spawn creatures and add more resources into making the armor such as an infinite antidote pill on the leggings and using lesser tier armors also.

**Comment by SpitefulFox** [comment]
ಠ_ಠ
