### ISSUE TITLE
avaritia recepie

### ISSUE THREAD

**Issue by MineProjectZ** [SpitefulFox/Avaritia#92]
my minetweaker recipe with the dire crafting table dont works: mods.avaritia.ExtremeCrafting.addShapeless(<ProjectE:item.pe_philosophers_stone>, [<ExtraUtilities:unstableingot:2>, <DraconicEvolution:chaoticCore>, <ore:ingotBedrockium>, <Botania:spreader:3>, <usefulDNS:PStone>, <baublelicious:entangledRing>, <RandomThings:ingredient:4>, <AWWayofTime:transcendentBloodOrb>, <ore:RotaryCraft:ingotBedrock>, <Mimicry:Sparr_Mimic Block>, <RArm:ItemMaterials>, <usefulDNS:UnobtainIngot>, <RedstoneArsenal:material:32>, <ExtraUtilities:generator.64:11>, <ExtraUtilities:mini-soul:3>, <SolarExpansion:solarPanelUltimate>, <TardisMod:item.TardisMod.CraftingComponent>, <TardisMod:item.TardisMod.CraftingComponent:1>, <GalacticraftCore:item.meteoricIronIngot>, <rftools:dimensionalShardItem>, <magicalcrops:magicalcrops_InfusionStone:4>, <headcrumbs:head>.withTag({SkullOwner: {Name: "tilera"}}), <Mekanism:TeleportationCore>, <Avaritia:Resource:6>, <TConstruct:heartCanister:5>]);

**Comment by Alexismachina** [comment]
1. Please do not post the same type of issue twice.
2. The minetweaker recipe syntax is wrong again. Please go on the minetweaker wiki to check for your recipe.

**Comment by MineProjectZ** [comment]
can you read? i have osted 2 differend recipes. and i was on minetweaker wiki but i cant find an other syntax.

**Comment by SpitefulFox** [comment]
Itemstacks are supposed to be surrounded by <>

**Comment by MineProjectZ** [comment]
i have surounded it, but  when i copy and paste it on github, it isnt there.

**Comment by SpitefulFox** [comment]
Yup.  It ate mine too.

**Comment by SpitefulFox** [comment]
I'm not seeing any problems with these.  Can you post the Minetweaker log?  Preferrably in pastebin.

**Comment by MineProjectZ** [comment]
http://pastebin.com/dsgDSZ3a

**Comment by SpitefulFox** [comment]
The log indicates that a recipe for the philosopher's stone was added.  Also, really don't need two issues for the same thing.

**Comment by MineProjectZ** [comment]
It isnt the same thing and i cnat craft the philosopher stone.

**Comment by MineProjectZ** [comment]
And the log sais, the recipe is added but the recipe is unadded.
