### ISSUE TITLE
recipe error

### ISSUE THREAD

**Issue by MineProjectZ** [SpitefulFox/Avaritia#93]
what is wrong with this recipe: mods.avaritia.ExtremeCrafting.addShaped(Mekanism:EnergyCube:1.withTag({tier: "Creative", electricity: 2.147483647E9}), [[ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3], [ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul], [ProjectE:collector_mk3, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), ExtraUtilities:mini-soul, headcrumbs:head.withTag({SkullOwner: {Name: "HunterBrownTJ"}}), headcrumbs:head.withTag({SkullOwner: {Name: "tilera"}}), headcrumbs:head.withTag({SkullOwner: {Name: "Sir1Baldur"}}), ExtraUtilities:mini-soul, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), ProjectE:collector_mk3], [ProjectE:collector_mk3, ExtraUtilities:mini-soul, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), headcrumbs:head.withTag({SkullOwner: {Name: "Jens10123"}}), DraconicEvolution:reactorStabilizer, headcrumbs:head.withTag({SkullOwner: {Name: "CTekkLP"}}), DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), ExtraUtilities:mini-soul, ProjectE:collector_mk3], [ProjectE:collector_mk3, ExtraUtilities:mini-soul, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), DraconicEvolution:reactorStabilizer, DraconicEvolution:reactorCore, DraconicEvolution:reactorStabilizer, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), ExtraUtilities:mini-soul, ProjectE:collector_mk3], [ProjectE:collector_mk3, ExtraUtilities:mini-soul, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), headcrumbs:head.withTag({SkullOwner: {Name: "Pyramidalist"}}), DraconicEvolution:reactorStabilizer, headcrumbs:head.withTag({SkullOwner: {Name: "DebitorLP"}}), DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), ExtraUtilities:mini-soul, ProjectE:collector_mk3], [ProjectE:collector_mk3, ExtraUtilities:mini-soul, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), headcrumbs:head.withTag({SkullOwner: {Name: "BevoLJ"}}), Mekanism:EnergyCube:100.withTag({tier: "Creative"}), ExtraUtilities:generator.64:11, DraconicEvolution:draconiumFluxCapacitor:1.withTag({Energy: 250000000}), ExtraUtilities:mini-soul ProjectE:collector_mk3], [ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul, ExtraUtilities:mini-soul], [ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3, ProjectE:collector_mk3]]);

**Comment by F4ndroid** [comment]
Syntax is wrong.

http://minetweaker3.powerofbytes.com/wiki/Tutorial:Basic_Recipes

**Comment by MineProjectZ** [comment]
there is no syntax for avaritia on this webside.

**Comment by SpitefulFox** [comment]
I'm not seeing any problems with these.  Can you post the Minetweaker log?  Preferrably in pastebin.

**Comment by MineProjectZ** [comment]
http://pastebin.com/dsgDSZ3a

**Comment by SpitefulFox** [comment]
I'm seeing a compressor recipe being added for the energy cube.  Did you change it to compressor instead?

**Comment by MineProjectZ** [comment]
No. The compressor recipe ist for the empty energy cube.

**Comment by F4ndroid** [comment]
Can you give us a copy of the script(s)? Also, be sure you have the right item names. If you're unsure, hold the item in your hand and run "/mt hand" to get the full internal name of the item.

**Comment by MineProjectZ** [comment]
http://pastebin.com/19Z8PkZc

**Comment by F4ndroid** [comment]
http://pastebin.com/p9TnNDG4

This should fix it.
