### ISSUE TITLE
Are we allowed to make addons for this mod?

### ISSUE THREAD

**Issue by ChristoCoder** [SpitefulFox/Avaritia#98]
Is it okay to make addons for your mod?

**Comment by RCXcrafter** [comment]
I don't see why not, here's two addons that already exist:
http://minecraft.curseforge.com/projects/thermal-singularities
http://minecraft.curseforge.com/projects/rmkpack-s-xtrememodtweaks

**Comment by SpitefulFox** [comment]
Yes, you're allowed.
